name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache: true

      - name: Run tests
        run: go test -v ./...

      - name: Verify module
        run: |
          GOPROXY=proxy.golang.org go list -m github.com/ymc-github/go-editjsonns@${{ github.ref_name }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          body: |
            Please refer to [CHANGELOG.md](./CHANGELOG.md) for details.
            
            ### Installation
            ```bash
            go get github.com/ymc-github/go-editjsonns@${{ github.ref_name }}
            ```
            
            View on [pkg.go.dev](https://pkg.go.dev/github.com/ymc-github/go-editjsonns@${{ github.ref_name }})

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            yemiancheng/go-editjsonns:latest
            yemiancheng/go-editjsonns:${{ github.ref_name }} 